version: '3.8'

services:
  fox-deck-app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "80:80"
#  fox-deck-api:
#    build:
#      context: .
#      dockerfile: api.Dockerfile
#    ports:
#      - "3000:3000"
  db:
    container_name: fox-deck-db
    build:
      context: ./apps/fox-deck-db
      dockerfile: db.Dockerfile
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --authentication-policy=mysql_native_password
    restart: always
    volumes:
      - "./apps/fox-deck-db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fdadmin