/**
 * Contains the icons we are using through the application.
 * Please try to sort the icons alphabetically.
 */
export enum Icon {
  CARET_RIGHT = "fi-rr-caret-right",
  CARET_DOWN = "fi-rr-caret-down",
  CHECK = "fi-rr-check",
  CHEVRON_DOUBLE_RIGHT = "fi-rr-angle-double-right",
  CHEVRON_DOUBLE_LEFT = "fi-rr-angle-double-left",
  CHEVRON_LEFT = "fi-rr-angle-left",
  CHEVRON_RIGHT = "fi-rr-angle-right",
  CHEVRON_DOWN = "fi-rr-angle-down",
  DELETE = "fi-rr-trash",
  DOCUMENT = "fi-rr-document",
  DOCUMENT_FILLED = "fi-sr-document",
  EDIT = "fi-rr-edit",
  FILTER = "fi-rr-filter",
  FOLDER = "fi-rr-folder",
  FOLDER_FILLED = "fi-sr-folder",
  FOLDER_FILLED_OPEN = "fi-rr-folder-open",
  GRADUATION = "fi-rr-graduation-cap",
  HOME = "fi-rr-home",
  LOADING = "fi-rr-loading",
  MENU_VERTICAL = "fi-rr-menu-dots-vertical",
  MENU_BURGER = "fi-rr-menu-burger",
  PLUS = "fi-rr-plus",
  THUMBTACK = "fi-rr-thumbtack",
  THUMBTACK_FILLED = "fi-sr-thumbtack",
  QUESTION = "fi-rr-lightbulb-question",
  SAVE = "fi-rr-disk",
  SAVE_FILLED = "fi-sr-disk",
  SEARCH = "fi-rr-search",
  SIGN_OUT = "fi-rr-exit",
  SIGN_IN = "fi-rr-enter",
  SETTINGS = "fi-rr-settings",
  SPINNER = "fi-rr-spinner",
  STAR = "fi-rr-star",
  STAR_FILLED = "fi-sr-star",
  SUN = "fi-rr-sun",
  MOON = "fi-rr-moon",
  WARNING = "fi fi-rr-triangle-warning",
  X = "fi-rr-cross"
}