site:
  title: Foxdeck docs
  start_page: foxdeck::intro.adoc
content:
  sources:
    - url: ./../
      start_path: docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true