== Code Guidelines

In our project, ESLint is an integral part of the development process. It ensures that all code contributions adhere to a unified standard, reducing the likelihood of syntax-related bugs and enhancing code readability and maintainability. The ESLint configuration has been tailored to our specific coding practices and is regularly updated to reflect changes in our coding standards and the evolving JavaScript ecosystem.

=== What is ESLint?

ESLint is a powerful and widely-used static analysis tool for identifying problematic patterns found in JavaScript code. It's not limited to just flagging potential errors; it also offers solutions for syntax that doesn't adhere to certain style guidelines. ESLint is highly configurable, allowing teams to adjust the rules to their specific coding standards and workflows.

1. *Code Consistency:* ESLint helps maintain a consistent code style across the entire project. This consistency is crucial in a team environment where multiple developers contribute to the same codebase.

2. *Early Error Detection:* By identifying syntax errors and problematic patterns early, ESLint saves time in the debugging process. Catching errors at the coding stage is much more efficient than discovering them later in testing or production.

3. *Improved Code Quality:* ESLint's rules encourage good coding practices and patterns, which can lead to an overall improvement in code quality. It encourages best practices like using const for constants, or preventing unused variables.

4. *Customizable Rules:* One of the key strengths of ESLint is its flexibility. Teams can customize rules to suit their project's needs, which means ESLint can be adapted as the project evolves.

5. *Integration with Development Environments:* ESLint integrates seamlessly into most development environments and build processes. It can be run as part of continuous integration (CI) pipelines, ensuring that all committed code adheres to the team's coding standards.

6. *Auto-fixing:* ESLint can automatically fix some of the problems it detects, which is a significant time-saver. This feature can be used in both local development environments and as part of CI/CD pipelines.

=== How to use ESLint locally?

In our project, we have incorporated ESLint to ensure code quality and consistency. To facilitate this, we have two specific npm script commands that can be used locally by developers to find and fix ESLint errors.

==== Finding ESLint Errors

To identify ESLint errors in the codebase, you can use the following command:

[source, bash]
----
// [root directory]
$ npm run lint
----

This command runs ESLint on all files in the apps directory and its subdirectories. It scans the JavaScript files for any code that doesn't comply with the defined ESLint rules. The output will list any issues found, along with their locations and descriptions. This is particularly useful for quickly identifying areas of the code that need attention.

==== Automatically Fixing ESLint Errors

For convenience, we also have a command that not only identifies ESLint errors but also attempts to fix them automatically:

[source, bash]
----
// [root directory]
$ npm run lint:fix
----

When you run this command, ESLint will go through the code and automatically fix any issues that can be resolved without human intervention. This could include formatting issues, unused variables, and other simple errors. It's a great time-saver, helping to maintain code quality without bogging down the development process.

IMPORTANT: These commands are only available on the root level of the project.