= Foxdeck: Developer Guide
:toc:

IMPORTANT: Please note that this documentation is currently in progress and may not yet be complete. We are actively working to update and expand its contents to ensure it provides the most accurate and comprehensive information.

== About this Document

This document provides a comprehensive guide to the software's architecture, highlighting key components and their interactions to facilitate efficient development and collaboration.
It is designed to help developers build an understanding of the code and its philosophies in order to help shape and extend the software.

== Our goal

We want to help students organizing their class notes, lecture summaries and study materials and create questions about these topics to help remembering all the things.

== Getting started

=== Prerequisites

- [NodeJS](https://nodejs.org/en)

=== Installation

We've built a script, which handles all the initial setup of your development environment by itself. You
can start the script by running following console command:

[source,bash]
----
$ npm run setup:dev
----

== Understanding the basic structure

One of the most difficult things is to find your way around the code of other developers.
In order to gain a deep understanding of the software, it is important to understand and comprehend the thoughts of the developers.

Foxdeck was initially planned as a small application in which simple questions can be created for learning purposes.
In the course of development, however, it has become clear that the software has greater potential to be offered to a wider audience.
For this purpose, the initially very flat hierarchy and a JSON file as a "database" was turned into a deeper hierarchy with two software parts: the interface "fox-deck-app" and the back-end "fox-deck-api".
These two parts are located in the folder hierarchy in the "apps" folder.