name: Testing - fox-deck-api

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # testing the fox-deck frontend
  test_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/fox-deck-api
    name: Run API Unit Tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run test