name: Testing - fox-deck-app

on:
  pull_request:
    branches:
      - master

jobs:
  # testing the fox-deck frontend
  test_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/fox-deck-app
    name: Run App Unit Tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Rename environment file
        run: mv .env.example .env
      - run: npm ci
      - run: npm run test:unit