name: Deploy to production

on:
  workflow_dispatch:

jobs:
  deploy_to_production:
    if: contains('["dominique-boerner", "Eric-Schubert"]', github.actor)
    runs-on: ubuntu-latest
    name: Deploy to docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest