name: Deploy to dev

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  # testing the fox-deck frontend
  test_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/fox-deck-app
    name: Test - Front-End
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run test:unit

  # testing the fox-deck api
  test_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/fox-deck-api
    name: Test - API
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Rename environment file
        run: mv .env.example .env
      - run: npm ci
      - run: npm run test

  # build and deploy the documentation
  deploy_docs:
    runs-on: ubuntu-latest
    name: Generate and deploy developer documentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ⚙️ Build documentation
        run:  npm run docs
      - name: 📂 Upload documentation via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_DEV_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './docs/build/site/*'
          remote_path: '/var/www/docs'
          sftp_only: true

  # build and deploy the app
  deploy_app:
    runs-on: ubuntu-latest
    name: Build and deploy the app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run install:app
      - name: ⚙️ Build app
        run:  npm run build:app
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"
      - name: 📂 Upload fox-deck-app via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_DEV_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './apps/fox-deck-app/dist/*'
          remote_path: '/var/www/dev'
          sftp_only: true